### ISSUE TITLE
Why use std::abs here?

### ISSUE THREAD

**Issue by zhouhang95** [InteractiveComputerGraphics/TriangleMeshDistance#2]
https://github.com/InteractiveComputerGraphics/TriangleMeshDistance/blob/4eefe274bee688c2dfaf0fbc61ca19bfec9cf6c1/TriangleMeshDistance/include/tmd/TriangleMeshDistance.h#L379

dot -> abs -> acos

the result angle is [0, pi/2]

i think it is this

dot -> acos -> if angle > 0 then angle else pi + angle

**Comment by JoseAntFer** [comment]
Hello,

you are right. The abs function should not be used there. The range of the normalized dot product is [-1, 1] which maps to [0, pi].

Thanks for pointing this out.
Best regards,
José.
