### ISSUE TITLE
Interested in adding tag to the library?

### ISSUE THREAD

**Issue by traversaro** [InteractiveComputerGraphics/TriangleMeshDistance#3]
Hello @JoseAntFer, thanks a lot for working on this library! 

I am interesting in adding a package for this library in [conda-forge](https://conda-forge.org/) (a community maintained distribution of software and libraries for Windows/macOS/Linux), mainly as it is a dependency of https://github.com/UPC-ViRVIG/SdfLib that is a dependency of https://github.com/google-deepmind/mujoco . 

As I need to assign a "version number" to the package, I was wondering if you are interested in adding git tags to the library, to mark specific point of history of the repo. If you are not interested in this, no problem, I can assign an arbitrary version number to a given commit (typically based on [calver](https://calver.org/)), but I wanted to first check with you before assigning an arbitrary version.

Thanks a lot in advance!

**Comment by JoseAntFer** [comment]
Dear @traversaro,

I am happy to hear people find our library useful. I added a new release with the tag 'v1.0.0'.

Best regards,
José.

**Comment by traversaro** [comment]
Great @JoseAntFer, thanks a lot!
