### ISSUE TITLE
confused about the point_triangle_sq_unsigned function

### ISSUE THREAD

**Issue by jlxy11** [InteractiveComputerGraphics/TriangleMeshDistance#4]
I don't quite understand this function. Can you give me some information on its principles?
static double tmd::point_triangle_sq_unsigned（）.

**Comment by JoseAntFer** [comment]
Hi,

I documented the function in the original source code. When you give a point in space and the three vertices of a triangle, this function will return the squared distance from the point to the triangle and also which was the nearest feature of the triangle to the point and also the coordinates of the closest point on the triangle to your original query point.

I hope this helps :)

**Comment by jlxy11** [comment]
Thanks a lot for your reply and sorry for the delay,  I read your code and I found that your method of dividing the seven areas of the triangle according to the extension lines of the sides is too complicated. I learned that the seven areas can be divided according to the perpendiculars of the sides of the triangle, so that the code should be simpler, I'm not sure if this is possible, can you help me figure it out? In the article you mentioned, they are also divided according to vertical 
（Generating Signed Distance Fields From Triangle Meshes）
http://www2.imm.dtu.dk/pubdb/edoc/imm1289.pdf
（iquilezles triangle distance）
https://iquilezles.org/articles/distfunctions/
@JoseAntFer

**Comment by JoseAntFer** [comment]
The code you refer to was inherited from a different project and I did not write it myself. It has been extensively tested and used in this and other applications, but I sadly cannot help you untangling it. Also, I don't really have spare time to simplifying it or improving it in any way at the moment.

In any case, thank you for pointing it out. I will have it in mind.

**Comment by jlxy11** [comment]
> The code you refer to was inherited from a different project and I did not write it myself. It has been extensively tested and used in this and other applications, but I sadly cannot help you untangling it. Also, I don't really have spare time to simplifying it or improving it in any way at the moment.
> 
> In any case, thank you for pointing it out. I will have it in mind.

Thank you for your replying! I will try to do this work.

**Comment by jlxy11** [comment]
> The code you refer to was inherited from a different project and I did not write it myself. It has been extensively tested and used in this and other applications, but I sadly cannot help you untangling it. Also, I don't really have spare time to simplifying it or improving it in any way at the moment.
> 
> In any case, thank you for pointing it out. I will have it in mind.

Thank you for your replying! maybe I will do this work.
