### ISSUE TITLE
_build_tree: Sort the triangles along the split dimension

### ISSUE THREAD

**Issue by bigbike** [InteractiveComputerGraphics/TriangleMeshDistance#5]
Is it a bug? The comment says "Sort the triangles according to their center along the split dimension" but it actually sorts them based on vertex 0?

https://github.com/InteractiveComputerGraphics/TriangleMeshDistance/blob/f66ad12cc0d201d299c76e460f5a355e768bf6dc/TriangleMeshDistance/include/tmd/TriangleMeshDistance.h#L488-L494

**Comment by JoseAntFer** [comment]
Hi. That was simply an old comment that was never corrected. I updated it now. Thanks for pointing that up! :)
